[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
